# Generated by Django 4.0.5 on 2022-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_accounttiers_user_acc_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttiers',
            name='name',
            field=models.CharField(choices=[('BS', 'Basic'), ('PR', 'Premium'), ('EP', 'Enterprise')], default='BS', max_length=100, unique=True),
        ),
    ]
