# Generated by Django 4.0.5 on 2022-06-30 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_accounttiers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_tier',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.accounttiers'),
        ),
    ]
